In [ ]:
#import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
 #WorldCupMatches new (1).csv

from google.colab import drive
drive.mount('/content/drive/')

Mounted at /content/drive/


In [63]:
import pandas as pd
import numpy as np
path="/content/drive/MyDrive/WorldCupMatches.csv"
dataset=pd.read_csv(path)
print(dataset)

     Year              Datetime                     Stage  \
0    1930  13 Jul 1930 - 15:00                    Group 1   
1    1930  13 Jul 1930 - 15:00                    Group 4   
2    1930  14 Jul 1930 - 12:45                    Group 2   
3    1930  14 Jul 1930 - 14:50                    Group 3   
4    1930  15 Jul 1930 - 16:00                    Group 1   
..    ...                   ...                       ...   
847  2014  05 Jul 2014 - 17:00             Quarter-finals   
848  2014  08 Jul 2014 - 17:00                Semi-finals   
849  2014  09 Jul 2014 - 17:00                Semi-finals   
850  2014  12 Jul 2014 - 17:00   Play-off for third place   
851  2014  13 Jul 2014 - 16:00                      Final   

                 Stadium             City Home Team Name  Home Team Goals  \
0                Pocitos      Montevideo          France                4   
1         Parque Central      Montevideo             USA                3   
2         Parque Central      Montev

In [ ]:
#import pandas as pd
#import numpy as np
path="/content/drive/MyDrive/WorldCupMatches.csv"
dataset = pd.read_csv(path)



dataset.head()


Year              Datetime    Stage         Stadium         City  \
0  1930  13 Jul 1930 - 15:00   Group 1         Pocitos  Montevideo    
1  1930  13 Jul 1930 - 15:00   Group 4  Parque Central  Montevideo    
2  1930  14 Jul 1930 - 12:45   Group 2  Parque Central  Montevideo    
3  1930  14 Jul 1930 - 14:50   Group 3         Pocitos  Montevideo    
4  1930  15 Jul 1930 - 16:00   Group 1  Parque Central  Montevideo    

  Home Team Name  Home Team Goals  Away Team Goals Away Team Name  \
0         France                4                1         Mexico   
1            USA                3                0        Belgium   
2     Yugoslavia                2                1         Brazil   
3        Romania                3                1           Peru   
4      Argentina                1                0         France   

  Win conditions  Attendance  Half-time Home Goals  Half-time Away Goals  \
0                     4444.0                     3                     0   
1                    18346.0                     2                     0   
2                    24059.0                     2                     0   
3                     2549.0                     1                     0   
4                    23409.0                     0                     0   

                  Referee               Assistant 1  \
0  LOMBARDI Domingo (URU)     CRISTOPHE Henry (BEL)   
1       MACIAS Jose (ARG)  MATEUCCI Francisco (URU)   
2     TEJADA Anibal (URU)   VALLARINO Ricardo (URU)   
3   WARNKEN Alberto (CHI)       LANGENUS Jean (BEL)   
4     REGO Gilberto (BRA)      SAUCEDO Ulises (BOL)   

                  Assistant 2  RoundID  MatchID Home Team Initials  \
0         REGO Gilberto (BRA)      201     1096                FRA   
1       WARNKEN Alberto (CHI)      201     1090                USA   
2         BALWAY Thomas (FRA)      201     1093                YUG   
3    MATEUCCI Francisco (URU)      201     1098                ROU   
4  RADULESCU Constantin (ROU)      201     1085                ARG   

  Away Team Initials  
0                MEX  
1                BEL  
2                BRA  
3                PER  
4                FRA

In [ ]:
dataset.shape

(852, 20)

In [ ]:
dataset=dataset.set_index('Datetime')

In [ ]:
dataset.columns

Index(['Year', 'Stage', 'Stadium', 'City', 'Home Team Name', 'Home Team Goals',
       'Away Team Goals', 'Away Team Name', 'Win conditions', 'Attendance',
       'Half-time Home Goals', 'Half-time Away Goals', 'Referee',
       'Assistant 1', 'Assistant 2', 'RoundID', 'MatchID',
       'Home Team Initials', 'Away Team Initials'],
      dtype='object')

In [ ]:
dataset.dtypes

Year                      int64
Stage                    object
Stadium                  object
City                     object
Home Team Name           object
Home Team Goals           int64
Away Team Goals           int64
Away Team Name           object
Win conditions           object
Attendance              float64
Half-time Home Goals      int64
Half-time Away Goals      int64
Referee                  object
Assistant 1              object
Assistant 2              object
RoundID                   int64
MatchID                   int64
Home Team Initials       object
Away Team Initials       object
dtype: object

In [ ]:
# Slice the result for first 5 rows
print (dataset[0:5]['City'])

Datetime
13 Jul 1930 - 15:00     Montevideo 
13 Jul 1930 - 15:00     Montevideo 
14 Jul 1930 - 12:45     Montevideo 
14 Jul 1930 - 14:50     Montevideo 
15 Jul 1930 - 16:00     Montevideo 
Name: City, dtype: object


In [ ]:
# Reading Specific Columns
print (dataset.loc[:,['Stadium','City']])

                                  Stadium             City
Datetime                                                  
13 Jul 1930 - 15:00               Pocitos      Montevideo 
13 Jul 1930 - 15:00        Parque Central      Montevideo 
14 Jul 1930 - 12:45        Parque Central      Montevideo 
14 Jul 1930 - 14:50               Pocitos      Montevideo 
15 Jul 1930 - 16:00        Parque Central      Montevideo 
...                                   ...              ...
05 Jul 2014 - 17:00      Arena Fonte Nova        Salvador 
08 Jul 2014 - 17:00      Estadio Mineirao  Belo Horizonte 
09 Jul 2014 - 17:00    Arena de Sao Paulo       Sao Paulo 
12 Jul 2014 - 17:00      Estadio Nacional        Brasilia 
13 Jul 2014 - 16:00   Estadio do Maracana  Rio De Janeiro 

[852 rows x 2 columns]


In [ ]:
#Reading Specific Columns and Rows
#print (dataset.loc[1:6,['Stadium','City']])

In [ ]:
#Reading Specific Columns and Rows
#print (dataset.loc[[1,3,5],['Stadium','City']])

In [ ]:
#showing all null values
dataset.isnull() 

Year  Stage  Stadium   City  Home Team Name  \
Datetime                                                             
13 Jul 1930 - 15:00   False  False    False  False           False   
13 Jul 1930 - 15:00   False  False    False  False           False   
14 Jul 1930 - 12:45   False  False    False  False           False   
14 Jul 1930 - 14:50   False  False    False  False           False   
15 Jul 1930 - 16:00   False  False    False  False           False   
...                     ...    ...      ...    ...             ...   
05 Jul 2014 - 17:00   False  False    False  False           False   
08 Jul 2014 - 17:00   False  False    False  False           False   
09 Jul 2014 - 17:00   False  False    False  False           False   
12 Jul 2014 - 17:00   False  False    False  False           False   
13 Jul 2014 - 16:00   False  False    False  False           False   

                      Home Team Goals  Away Team Goals  Away Team Name  \
Datetime                                                                 
13 Jul 1930 - 15:00             False            False           False   
13 Jul 1930 - 15:00             False            False           False   
14 Jul 1930 - 12:45             False            False           False   
14 Jul 1930 - 14:50             False            False           False   
15 Jul 1930 - 16:00             False            False           False   
...                               ...              ...             ...   
05 Jul 2014 - 17:00             False            False           False   
08 Jul 2014 - 17:00             False            False           False   
09 Jul 2014 - 17:00             False            False           False   
12 Jul 2014 - 17:00             False            False           False   
13 Jul 2014 - 16:00             False            False           False   

                      Win conditions  Attendance  Half-time Home Goals  \
Datetime                                                                 
13 Jul 1930 - 15:00            False       False                 False   
13 Jul 1930 - 15:00            False       False                 False   
14 Jul 1930 - 12:45            False       False                 False   
14 Jul 1930 - 14:50            False       False                 False   
15 Jul 1930 - 16:00            False       False                 False   
...                              ...         ...                   ...   
05 Jul 2014 - 17:00            False       False                 False   
08 Jul 2014 - 17:00            False       False                 False   
09 Jul 2014 - 17:00            False       False                 False   
12 Jul 2014 - 17:00            False       False                 False   
13 Jul 2014 - 16:00            False       False                 False   

                      Half-time Away Goals  Referee  Assistant 1  Assistant 2  \
Datetime                                                                        
13 Jul 1930 - 15:00                  False    False        False        False   
13 Jul 1930 - 15:00                  False    False        False        False   
14 Jul 1930 - 12:45                  False    False        False        False   
14 Jul 1930 - 14:50                  False    False        False        False   
15 Jul 1930 - 16:00                  False    False        False        False   
...                                    ...      ...          ...          ...   
05 Jul 2014 - 17:00                  False    False        False        False   
08 Jul 2014 - 17:00                  False    False        False        False   
09 Jul 2014 - 17:00                  False    False        False        False   
12 Jul 2014 - 17:00                  False    False        False        False   
13 Jul 2014 - 16:00                  False    False        False        False   

                      RoundID  MatchID  Home Team Initials  Away Team Initials  
Datetime                                           

In [ ]:
dataset.isnull().values.any()

True

In [ ]:
dataset.isnull().sum()

Year                    0
Stage                   0
Stadium                 0
City                    0
Home Team Name          0
Home Team Goals         0
Away Team Goals         0
Away Team Name          0
Win conditions          0
Attendance              0
Half-time Home Goals    0
Half-time Away Goals    0
Referee                 0
Assistant 1             0
Assistant 2             0
RoundID                 0
MatchID                 0
Home Team Initials      0
Away Team Initials      0
dtype: int64

In [ ]:
print(dataset['Attendance'].isnull())

Datetime
13 Jul 1930 - 15:00     False
13 Jul 1930 - 15:00     False
14 Jul 1930 - 12:45     False
14 Jul 1930 - 14:50     False
15 Jul 1930 - 16:00     False
                        ...  
05 Jul 2014 - 17:00     False
08 Jul 2014 - 17:00     False
09 Jul 2014 - 17:00     False
12 Jul 2014 - 17:00     False
13 Jul 2014 - 16:00     False
Name: Attendance, Length: 850, dtype: bool


In [ ]:
# filling missing value using fillna()   
dataset.fillna(0) 

Year                     Stage              Stadium  \
Datetime                                                                    
13 Jul 1930 - 15:00   1930                   Group 1              Pocitos   
13 Jul 1930 - 15:00   1930                   Group 4       Parque Central   
14 Jul 1930 - 12:45   1930                   Group 2       Parque Central   
14 Jul 1930 - 14:50   1930                   Group 3              Pocitos   
15 Jul 1930 - 16:00   1930                   Group 1       Parque Central   
...                    ...                       ...                  ...   
05 Jul 2014 - 17:00   2014            Quarter-finals     Arena Fonte Nova   
08 Jul 2014 - 17:00   2014               Semi-finals     Estadio Mineirao   
09 Jul 2014 - 17:00   2014               Semi-finals   Arena de Sao Paulo   
12 Jul 2014 - 17:00   2014  Play-off for third place     Estadio Nacional   
13 Jul 2014 - 16:00   2014                     Final  Estadio do Maracana   

                                 City Home Team Name  Home Team Goals  \
Datetime                                                                
13 Jul 1930 - 15:00       Montevideo          France                4   
13 Jul 1930 - 15:00       Montevideo             USA                3   
14 Jul 1930 - 12:45       Montevideo      Yugoslavia                2   
14 Jul 1930 - 14:50       Montevideo         Romania                3   
15 Jul 1930 - 16:00       Montevideo       Argentina                1   
...                               ...            ...              ...   
05 Jul 2014 - 17:00         Salvador     Netherlands                0   
08 Jul 2014 - 17:00   Belo Horizonte          Brazil                1   
09 Jul 2014 - 17:00        Sao Paulo     Netherlands                0   
12 Jul 2014 - 17:00         Brasilia          Brazil                0   
13 Jul 2014 - 16:00   Rio De Janeiro         Germany                1   

                      Away Team Goals Away Team Name  \
Datetime                                               
13 Jul 1930 - 15:00                 1         Mexico   
13 Jul 1930 - 15:00                 0        Belgium   
14 Jul 1930 - 12:45                 1         Brazil   
14 Jul 1930 - 14:50                 1           Peru   
15 Jul 1930 - 16:00                 0         France   
...                               ...            ...   
05 Jul 2014 - 17:00                 0     Costa Rica   
08 Jul 2014 - 17:00                 7        Germany   
09 Jul 2014 - 17:00                 0      Argentina   
12 Jul 2014 - 17:00                 3    Netherlands   
13 Jul 2014 - 16:00                 0      Argentina   

                                             Win conditions  Attendance  \
Datetime                                                                  
13 Jul 1930 - 15:00                                              4444.0   
13 Jul 1930 - 15:00                                             18346.0   
14 Jul 1930 - 12:45                                             24059.0   
14 Jul 1930 - 14:50                                              2549.0   
15 Jul 1930 - 16:00                                             23409.0   
...                                                     ...         ...   
05 Jul 2014 - 17:00   Netherlands win on penalties (4 - 3)      51179.0   
08 Jul 2014 - 17:00                                             58141.0   
09 Jul 2014 - 17:00     Argentina win on penalties (2 - 4)      63267.0   
12 Jul 2014 - 17:00                                             68034.0   
13 Jul 2014 - 16:00           Germany win after extra time      74738.0   

                      Half-time Home Goals  Half-time Away Goals  \
Datetime                                                           
13 Jul 1930 - 15:00                      3                     0   
13 Jul 1930 - 15:00                      2                     0   
14 Jul 1930 - 12:45                      2                     0   
14 Jul 1930 - 14:50      

In [ ]:
# drop rows with missing values
dataset.dropna(inplace=True)
dataset.shape

(850, 19)

In [ ]:
# using imputer class
from sklearn.impute import SimpleImputer
data = np.array([[1, np.nan, 2], [2, 3, np.nan], [-1, 4, 2]])


In [ ]:
data

array([[ 1., nan,  2.],
       [ 2.,  3., nan],
       [-1.,  4.,  2.]])

In [ ]:
imp = SimpleImputer(strategy='mean')
imp.fit_transform(data)

array([[ 1. ,  3.5,  2. ],
       [ 2. ,  3. ,  2. ],
       [-1. ,  4. ,  2. ]])

In [ ]:
imp = SimpleImputer(strategy='median')
imp.fit_transform(data)

array([[ 1. ,  3.5,  2. ],
       [ 2. ,  3. ,  2. ],
       [-1. ,  4. ,  2. ]])

In [ ]:
imp = SimpleImputer(strategy='most_frequent')
imp.fit_transform(data)

array([[ 1.,  3.,  2.],
       [ 2.,  3.,  2.],
       [-1.,  4.,  2.]])

In [ ]:
dataset["Year"].mean()

1985.0211764705882

In [ ]:
dataset["Year"].tail()

Datetime
05 Jul 2014 - 17:00     2014
08 Jul 2014 - 17:00     2014
09 Jul 2014 - 17:00     2014
12 Jul 2014 - 17:00     2014
13 Jul 2014 - 16:00     2014
Name: Year, dtype: int64

In [ ]:
dataset["Year"].replace(np.NaN,dataset["Year"].mean)

Datetime
13 Jul 1930 - 15:00     1930
13 Jul 1930 - 15:00     1930
14 Jul 1930 - 12:45     1930
14 Jul 1930 - 14:50     1930
15 Jul 1930 - 16:00     1930
                        ... 
05 Jul 2014 - 17:00     2014
08 Jul 2014 - 17:00     2014
09 Jul 2014 - 17:00     2014
12 Jul 2014 - 17:00     2014
13 Jul 2014 - 16:00     2014
Name: Year, Length: 850, dtype: int64

In [ ]:
import numpy as np
X = np.random.uniform(0.0, 1.0, size=(10, 2))
Y = np.random.choice(('Male','Female'), size=(10))
X[0]

array([0.6818948 , 0.92571904])

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
yt = le.fit_transform(Y)
yt

array([1, 1, 0, 1, 0, 0, 1, 1, 1, 1])

In [ ]:
output = [1, 0, 1, 1, 0, 0]

In [62]:
decoded_output = [le.classes_[i] for i in output]

In [ ]:
decoded_output

['Male', 'Female', 'Male', 'Male', 'Female', 'Female']

In [ ]:
#one-hot encoding using LabelBinarizer class
from sklearn.preprocessing import LabelBinarizer
lb = LabelBinarizer()
Yb = lb.fit_transform(Y)

In [ ]:
Yb

array([[1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1]])

In [ ]:
lb.inverse_transform(Yb)

array(['Male', 'Male', 'Female', 'Male', 'Female', 'Female', 'Male',
       'Male', 'Male', 'Male'], dtype='<U6')

In [ ]:
from sklearn.preprocessing import OneHotEncoder
data =[
[0, 10],
[1, 11],
[1, 8],
[0, 12],
[0, 15]
]

In [ ]:
data

[[0, 10], [1, 11], [1, 8], [0, 12], [0, 15]]

In [ ]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.compose import ColumnTransformer 
oh =  ColumnTransformer( [('one_hot_encoder', OneHotEncoder(), [0])], remainder='passthrough')
Y_oh = oh.fit_transform(data)
#Y_oh.todense()